
# Menus
menu:
  ZenHub Boards: https://github.com/kudotty/kudotty.com#boards?repos=63670542
  SlideShare: http://www.slideshare.net/kudotty
  Qiita: http://qiita.com/kudotty
  半二重男女: http://half.kudotty.com/

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: /images/kudottyDevOps.logo.svg
    profile:
        enabled: true # Whether to show profile bar
        avatar: /images/kudottyDevOps.avatar.svg
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: '@kudotty'
        author_title: フルスタック色事師
        location: Tokyo, Japan
        follow: https://github.com/kudotty/
    highlight: monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: css/icons/favicon-16x16.png
    social_links:
        slideshare: http://www.slideshare.net/kudotty
        github: https://github.com/kudotty/
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - category
    - tag
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: kudotty # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    fancybox: false # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hackers Bar: http://hackers.bar/
